### ISSUE TITLE
Textarea still has a vertically centered label

### ISSUE THREAD

**Issue by gbeumer** [CastleCSS/castlecss-forms#23]
Textarea still has a vertically centered label this label should be placed at the top of the textarea

![image](https://user-images.githubusercontent.com/4817357/30859556-87e66306-a2c4-11e7-92bc-83de6df76259.png)

**Comment by dariusrosendahl** [comment]
Fixed in https://github.com/CastleCSS/castlecss-forms/pull/25

**Comment by dariusrosendahl** [comment]
Fixed in https://github.com/CastleCSS/castlecss-forms/releases/tag/v1.1.1
