### ISSUE TITLE
IE 10: Arrow in select not aligned correctly

### ISSUE THREAD

**Issue by Paulus90** [CastleCSS/castlecss-forms#45]
The arrow in the select element is not aligned correctly in IE10. The 'down' arrow is positioned too far to the right, the 'up' arrow is positioned too far to the left.

**Comment by pascalalferink** [comment]
I made changes. These changes can be found in #48

**Comment by dariusrosendahl** [comment]
Released in https://github.com/CastleCSS/castlecss-forms/releases/tag/v1.0.12
