### ISSUE TITLE
Default label not working in version 1.0.7

### ISSUE THREAD

**Issue by gbeumer** [CastleCSS/castlecss-forms#6]
Default label not above formfield but inside

Edit:
- The default placeholder needs to be hidden
 - The default label needs to dissapear when starting to type
 - When the default label disappears it should not be (much) slower then a native placeholder
 - When using the classes label-top , label-bottom or label-above the label should not disapear but move to their respective positions

**Comment by dariusrosendahl** [comment]
In 1.0.7 the default styling is not present. You always need to add a class like ```label-above```

**Comment by Paulus90** [comment]
Created pull request

**Comment by dariusrosendahl** [comment]
How it should work:

- [ ] - The default placeholder needs to be hidden
- [ ] - The default label needs to dissapear when starting to type
- [ ] - When the default label disappears it 
- [ ] - When using the classes ``label-top```, ```label-bottom``` or ```label-above``` the label should not disapear but move to their respective positions

Working on it in https://github.com/CastleCSS/castlecss-forms/tree/label-fixes

**Comment by dariusrosendahl** [comment]
Fixed and merged in https://github.com/CastleCSS/castlecss-forms/pull/20
