### ISSUE TITLE
Label inside input not correct for input type date, number and select

### ISSUE THREAD

**Issue by gbeumer** [CastleCSS/castlecss-forms#9]
Label inside input is on top of the default value for input type date, number and select with the classes .label-bottom, .label-top and .label-above

**Comment by Paulus90** [comment]
When pull request #14 is accepted, the input[type=number] and select elements won't have this issue anymore: 
- When you want to bind a label to a select element, just don't use the class 'placeholder' on the label. This way, the label won't be positioned on top of the select element.
- Input[type=number] already worked, just not when a label position wasn't specified. This is now fixed (in request #14).

**Comment by Paulus90** [comment]
Fix implemented in pull request #15

**Comment by dariusrosendahl** [comment]
#6 is merged in develop and will be implemented in the next release
